### ISSUE TITLE
TypeError when setting level: debug

### ISSUE THREAD

**Issue by fmmartins** [mcollina/pino#105]
When setting the `level` key to `debug` and running a node script, this error shows up:
```
Unhandled rejection TypeError: Cannot read property 'write' of null
    at LOG (/home/.../node_modules/pino/pino.js:381:9)
    at Sequelize.log (/home/.../node_modules/sequelize/lib/sequelize.js:1344:21)
    at Query.run (/home/.../node_modules/sequelize/lib/dialects/mysql/query.js:36:20)
    at /home/.../node_modules/sequelize/lib/sequelize.js:849:20
    at /home/.../node_modules/retry-as-promised/index.js:38:21
    at Promise._execute (/home/.../node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/home/.../node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/.../node_modules/bluebird/js/release/promise.js:77:14)
    at retryAsPromised (/home/.../node_modules/retry-as-promised/index.js:27:10)
    at /home/.../node_modules/sequelize/lib/sequelize.js:848:12
    at tryCatcher (/home/.../node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/.../node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/.../node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/.../node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/.../node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/.../node_modules/bluebird/js/release/async.js:138:16)
TypeError: Cannot read property 'write' of null
    at LOG (/home/.../node_modules/pino/pino.js:381:9)
    at Sequelize.log (/home/.../node_modules/sequelize/lib/sequelize.js:1344:21)
    at Query.run (/home/.../node_modules/sequelize/lib/dialects/mysql/query.js:36:20)
    at /home/.../node_modules/sequelize/lib/sequelize.js:849:20
    at /home/.../node_modules/retry-as-promised/index.js:38:21
    at Promise._execute (/home/.../node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/home/.../node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/.../node_modules/bluebird/js/release/promise.js:77:14)
    at retryAsPromised (/home/.../node_modules/retry-as-promised/index.js:27:10)
    at /home/.../node_modules/sequelize/lib/sequelize.js:848:12
    at tryCatcher (/home/.../node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/.../node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/.../node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/.../node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/.../node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/.../node_modules/bluebird/js/release/async.js:138:16)

npm ERR! Linux 4.4.23-1-lts
npm ERR! argv "/home/fmm/.nvm/versions/node/v6.5.0/bin/node" "/home/fmm/.nvm/versions/node/v6.5.0/bin/npm" "run" "reset"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ...@ reset: `./libs/reset.js`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the ...@ reset script './libs/reset.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ... package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./libs/reset.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ...
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ...
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/.../npm-debug.log

npm ERR! Linux 4.4.23-1-lts
npm ERR! argv "/home/fmm/.nvm/versions/node/v6.5.0/bin/node" "/home/fmm/.nvm/versions/node/v6.5.0/bin/npm" "run" "dev"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ...@ dev: `npm run reset && nodemon --watch http --watch core --watch libs --watch trade.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ...@ dev script 'npm run reset && nodemon --watch http --watch core --watch libs --watch trade.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ... package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run reset && nodemon --watch http --watch core --watch libs --watch trade.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ...
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ...
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/.../npm-debug.log
```

The logger is being initialized like so:

```javascript
const pino = require('pino')

const logger = pino({
  name: 'trade-platform',
  safe: true,
  timestamp: false,
  level: 'debug',
  serializers: {
    req: pino.stdSerializers.req,
    res: pino.stdSerializers.res
  }
})

module.exports = exports = logger
```

Is this a known bug? 
Thanks

**Comment by jsumners** [comment]
Have you supplied the `pino` instance to `Sequelize` via its `options.logging` option?

**Comment by mcollina** [comment]
Can you please attach a script to reproduce?

**Comment by jsumners** [comment]
@fmmartins are you still having this issue? Can you help us replicate with a sample script?

**Comment by jsumners** [comment]
Test script:

```js
// npm install pino sequelize sqlite3
'use strict'

const pino = require('pino')
const pretty = pino.pretty()
pretty.pipe(process.stdout)
const log = pino({level: 'debug', serializers: pino.stdSerializers}, pretty)

const Sequelize = require('sequelize')
const sql = new Sequelize({
  dialect: 'sqlite',
  logging: log.debug
})

sql.authenticate()
  .then(() => {
    log.info('connected!')
  })
  .catch((err) => log.error({err}))
```

Function from `Sequelize` that causes the error:

```js
Sequelize.prototype.log = function() {
  var args = Utils.sliceArgs(arguments)
    , last = Utils._.last(args)
    , options;

  if (last && Utils._.isPlainObject(last) && last.hasOwnProperty('logging')) {
    options = last;

    // remove options from set of logged arguments
    args.splice(args.length-1, 1);
  } else {
    options = this.options;
  }

  if (options.logging) {
    if (options.logging === true) {
      console.log('DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log');
      options.logging = console.log;
    }

    // second argument is sql-timings, when benchmarking option enabled
    if ((this.options.benchmark || options.benchmark) && options.logging === console.log) {
      args = [args[0] + ' Elapsed time: ' + args[1] + 'ms'];
    }

    options.logging.apply(null, args);
  }
};
```

Notice that `Sequelize` is invoking `log.debug` as `log.debug.apply(null, args)`. This is overriding the `this` reference within `log.debug` as `null`. It should be obvious that `null` is not a stream.

The shortest path to victory is to change the function you send to `Sequelize`:

```js
const sql = new Sequelize({
  dialect: 'sqlite',
  logging: function () {
    log.debug.apply(log, arguments)
  }
})
```

That's really just a hack, though. What you *should* do is open an issue with `Sequelize`, or send them a PR, that requests proper logging support be added. That is, they should accept an instance of a logger that conforms to standard logging interfaces (i.e. Log4j), as `pino` does, and then use that interface to do their logging.

**Comment by mcollina** [comment]
I think we are ok to close this now, let us know how things go with Sequelize.

**Comment by jsumners** [comment]
@fmmartins you can suggest that they use https://github.com/jsumners/abstract-logging

**Comment by rnstlange** [comment]
> The shortest path to victory is to change the function you send to `Sequelize`:
> 
> ```js
> const sql = new Sequelize({
>   dialect: 'sqlite',
>   logging: function () {
>     log.debug.apply(log, arguments)
>   }
> })
> ```
```js
 const sql = new Sequelize({
     dialect: 'sqlite',
     logging: log.debug.bind(log))
 })
```
