### ISSUE TITLE
Use pino.pretty directly?

### ISSUE THREAD

**Issue by jprichardson** [mcollina/pino#50]
I see https://github.com/mcollina/pino/#pretty, but I'd expect something like this work:

```js
var pino = require('pino')
var log = pino({
  name: 'app',
  safe: true
}, pino.pretty().pipe(process.stdout))

log.child({ widget: 'foo' }).info('hello')
log.child({ widget: 'bar' }).warn('hello 2')
```

The expectation is that this would log the 'pretty' version directly to the console. But I get an error:

```
/private/tmp/shit/node_modules/pino/pretty.js:111
    return levelColors[value.level](levels[value.level])
                      ^

TypeError: Cannot read property '30' of undefined
    at asColoredLevel (/private/tmp/shit/node_modules/pino/pretty.js:111:23)
    at DestroyableTransform.mapLine [as mapper] (/private/tmp/shit/node_modules/pino/pretty.js:91:62)
    at DestroyableTransform.transform [as _transform] (/private/tmp/shit/node_modules/split2/index.js:33:21)
    at DestroyableTransform.Transform._read (/private/tmp/shit/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/private/tmp/shit/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/private/tmp/shit/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/private/tmp/shit/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/private/tmp/shit/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at EventEmitter.Pino.write (/private/tmp/shit/node_modules/pino/pino.js:210:17)
    at EventEmitter.LOG (/private/tmp/shit/node_modules/pino/pino.js:293:10)
```

What am I doing wrong?

**Comment by mcollina** [comment]
The example above does not work (it does not even throw), because you are in fact passing `process.stdout` to pino.

This is an example on how to use `pretty`:

```js
'use strict'

var pino = require('pino')
var pretty = pino.pretty()
pretty.pipe(process.stdout)
var log = pino({
  name: 'app',
  safe: true
}, pretty)

log.child({ widget: 'foo' }).info('hello')
log.child({ widget: 'bar' }).warn('hello 2')
```

Anyway, I couldn't reproduce your error.
