### ISSUE TITLE
Invalid time value on JSON.stringify()

### ISSUE THREAD

**Issue by PatrickHeneise** [mcollina/pino#94]
Versions:
- "pino": "^2.9.0"
- node 6

start: `node app.js | pino`

line: `console.log(JSON.stringify({'hello': 'world'}))`

leads to:

```
myproj/node_modules/pino/pretty.js:115
    return new Date(time).toISOString()
                          ^

RangeError: Invalid time value
    at asISODate (myproj/node_modules/pino/pretty.js:115:27)
    at DestroyableTransform.mapLine [as mapper] (myproj/node_modules/pino/pretty.js:94:17)
    at DestroyableTransform.transform [as _transform] (myproj/node_modules/split2/index.js:33:21)
    at DestroyableTransform.Transform._read (myproj/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (myproj/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (myproj/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (myproj/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (myproj/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Socket.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)

```

**Comment by jsumners** [comment]
Please provide some information on your `app.js` and what it is doing to cause the issue.

**app.js**
```js
'use strict'

const log = require('pino')()
log.info({hello: 'world'})
```

```
[jsumners@sumners-osx] /tmp/26/pino-test
% node app.js| pino                
[2016-09-26T14:59:52.781Z] INFO (22531 on sumners-osx.int.clayton.edu):
    hello: "world"

[jsumners@sumners-osx] /tmp/26/pino-test
% node -v    
v6.6.0

[jsumners@sumners-osx] /tmp/26/pino-test
% pino -v    
2.11.0
```

**Comment by mcollina** [comment]
I think we should handle the case a time is missing in the prettifier. It is not an issue on the logger itself.

**Comment by jsumners** [comment]
Is there an ETA on `chops`?

**Comment by PatrickHeneise** [comment]
@jsumners it's not log.info, but console.log, which really shouldn't break / be influenced by pino

**Comment by jsumners** [comment]
I see. There's also a problem with no level being present. I'm working on it right now.

**Comment by mcollina** [comment]
@jsumners zero time to do it atm :(. Would you like to take a stab at that?

**Comment by jsumners** [comment]
@mcollina if I get some time myself I will look into it.
